### ISSUE TITLE
Criando ramificações

### ISSUE THREAD

**Issue by cassiobotaro** [pythonmg/hacktoberfest#11]
Como o material foi feito para ser didático, a etapa de criação de ramificação(branch) de funcionalidade foi omitido. Acho que deveriamos adicionar conteúdo sobre isto mostrando o passo a passo.
Duas coisas importantes aqui são:

- [ ]  criação de ramificação e abertura de pull request utilizando nova branch
- [ ] sincronização do fork com o repositório original

**Comment by fcpimenta** [comment]
Estou me propondo a criar essa documentação, começando já.

**Comment by cassiobotaro** [comment]
closed with #34
